### ISSUE TITLE
showing all level are selected but selected only 2 levels 

### ISSUE THREAD

**Issue by vp9112** [wployalty/wployalty_woo_discount_rules#2]
![image](https://github.com/wployalty/wployalty_woo_discount_rules/assets/113898119/9e28ebd5-41a7-454a-a927-074068a69c4b)
 i selected the level 2 and ultimate level 1 but here showing all level was selected but not showing the full name

**Comment by Mercypaul27** [comment]
Fixed
![image](https://github.com/user-attachments/assets/81473351-f483-46f5-8ebf-795d98a586a8)
