### ISSUE TITLE
not showing the all level only showing selected levels in the drop down

### ISSUE THREAD

**Issue by vp9112** [wployalty/wployalty_woo_discount_rules#3]
![image](https://github.com/wployalty/wployalty_woo_discount_rules/assets/113898119/f888ac38-9625-4f1b-9c5f-30bfa211387b)

**Comment by Mercypaul27** [comment]
Fixed
![image](https://github.com/user-attachments/assets/e6acf9dd-2371-4071-900c-50263b260bf2)
